### PR TITLE
 Add session state and conversation history tracking for efficient RAG( resolves #4)

### LINKED ISSUE #4: RAG Implementation: Efficient Memory Storage 🧠
### **What is Needed**
Contributors are needed to implement an efficient memory storage that will help to optimally tracks conversation history, even in scenarios involving multiple file uploads. Maintaining proper session state management. Session timeouts are an option. 

### **How to Contribute**
1. Get familiar with the scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs). 
2. **Test your code:** It is pertinent that you check your code runs smoothly before making a pull request.
3. **Create a Pull Request:** Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation. 

### **Getting Started**
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

### PR DESCRIPTION
**Pull request by Mukku27**
### Add Session State Management, Conversation History Tracking, and Efficient Memory Storage for RAG  #4 

---

### Description

This PR introduces significant improvements to the `Speak-To-Docs` Streamlit application, enabling efficient memory storage for Retrieval-Augmented Generation (RAG) by implementing session state management, conversation history tracking, and session timeout. These changes aim to enhance the application's handling of conversation contexts and optimize memory usage.

---

### Summary of Changes

1. **Session State Management**:
   - **Initialization**: Added session state variables for conversation history, session activity timestamp, and unique session ID.
   - **Timeout Check**: Implemented `check_session_timeout()` to reset session data (conversation history, session ID) after 30 minutes of inactivity.

2. **Conversation History Tracking**:
   - **Conversation History**: User inputs and AI responses are now stored in `conversation_history`, a session state variable.
   - **Prompt Context**: Conversation history, alongside retrieved document content, is included in the RAG prompt, improving response relevance.
   
3. **Efficient RAG Implementation**:
   - **Memory Optimization**: The last 5 conversation messages are included in the prompt, preventing excessive memory usage.
   - **Vector Store Integration**: `DocArrayInMemorySearch` is utilized for efficient document similarity searches, aiding RAG processing.

4. **User Experience Enhancements**:
   - **Session Timeout**: Implemented a timeout mechanism to reset conversation history and session ID after 30 minutes of inactivity.
   - **Conversation Display**: Added UI to display conversation history within the Streamlit app for improved user experience.

---

### CODE REVIEW

**Comment by Mukku27** [comment]
@Odeyiany2  Please review the changes, and if everything looks good, I would appreciate it if you could merge the PR.

**Review by Sammybams — CHANGES_REQUESTED** [review]
Thank you very much @Mukku27. Please kindly check #40. Streamlit already implements session timeout itself so we don't need to configure that. for the querying, we want to use the ConversationBufferMemory and RetrievalQA method from Langchain for the RAG Chain implementation. So if you can effect these in your changes, that would be great. Thank you very much.

**Comment by Mukku27** [comment]
Thank you for the feedback, @Sammybams! I'll go ahead and remove the session timeout configuration and implement the `ConversationBufferMemory` and `RetrievalQA` methods from LangChain for the RAG Chain as requested. I'll update the PR shortly with these changes. Thanks again!

**Comment by Mukku27** [comment]
> Thank you very much @Mukku27. Please kindly check #40. Streamlit already implements session timeout itself so we don't need to configure that. for the querying, we want to use the ConversationBufferMemory and RetrievalQA method from Langchain for the RAG Chain implementation. So if you can effect these in your changes, that would be great. Thank you very much.


@Sammybams . Please review #41, incorporating the requested changes: removed session timeout configuration per Streamlit’s handling, and updated RAG Chain implementation to use LangChain’s ConversationBufferMemory and RetrievalQA method for querying. Let me know if any further adjustments are needed. Thanks!"

**Comment by Sammybams** [comment]
> > Thank you very much @Mukku27. Please kindly check #40. Streamlit already implements session timeout itself so we don't need to configure that. for the querying, we want to use the ConversationBufferMemory and RetrievalQA method from Langchain for the RAG Chain implementation. So if you can effect these in your changes, that would be great. Thank you very much.
> 
> @Sammybams . Please review #41, incorporating the requested changes: removed session timeout configuration per Streamlit’s handling, and updated RAG Chain implementation to use LangChain’s ConversationBufferMemory and RetrievalQA method for querying. Let me know if any further adjustments are needed. Thanks!"

Alright @Mukku27.

**Pull request closed without merging**
