### PR TITLE
Enhancing RAG with Conversation History Awareness

### PR DESCRIPTION
**Pull request by SujitSakore**
This project aims to enhance the existing Retrieval-Augmented Generation (RAG) system by implementing conversation history awareness. The primary objective is to enable the system to effectively handle and respond to follow-up questions based on previous interactions, thereby ensuring a seamless flow of information. The solution will involve tracking and remembering conversation history, allowing for context-aware responses while managing performance efficiently, even during long conversations. Contributors will be guided through familiarizing themselves with the current RAG architecture, implementing the necessary features, testing the functionality, and submitting their improvements for integration. This project represents a significant step towards creating a more intelligent and responsive conversational AI experience.

### CODE REVIEW

**Comment by Sammybams** [comment]
Please kindly document all the changes and updates you have made here @SujitSakore.

**Comment by SujitSakore** [comment]
Hello, @Sammybams 

1.Update requirements.txt 
Enhanced the requirements.txt file by adding new dependencies necessary for the project. This update ensures that all contributors can easily install the required packages within their development environment.

2.Update speech_io.py
Made significant modifications to the speech_io.py file to enhance audio input/output functionalities. These improvements are crucial for facilitating effective user interaction within the RAG system.

3.Update main.py
Updated the main.py file, which serves as the application entry point. This update includes initializing the application, configuring routes, and integrating newly developed features to improve overall functionality.

4.Update rag_functions.py
Refined the rag_functions.py file to improve core functions related to the RAG system. Enhancements focus on optimizing processing logic and adding support for conversation history awareness, enabling more context-aware responses.

5.Merge branch 'main' into main
Merged the latest changes from the main branch into the current branch to ensure that ongoing work is synchronized with the most recent developments in the codebase. This practice helps maintain consistency and avoids potential conflicts in future updates.

**Review by Sammybams — CHANGES_REQUESTED** [review]
Thank you very much for your contribution @SujitSakore. You have changed a number of things and I think you are not very familiar or haven't familiarized yourself with Streamlit which is the python library we are going to be using for deployment as it works per session. So the id's of different users can't be stored somewhere in a dictionary. Each user session is unique to them and can't access info from that of others. Also you have cleared the major functions in the `speech_io.py` script that houses the transcription and synthesis of audio.

Kindly check all these out and work on an update. You can check out the `main.py` script to check out what has been implemented so far for the Streamlit frontend and also the Streamlit documentation. Thank you very much.

**Comment by SujitSakore** [comment]
Thank you @Sammybams for the feedback! I'm still in my learning phase, and I'll try to make the updates as mentioned. Thanks again for all your support!

**Comment by Sammybams** [comment]
> Thank you @Sammybams for the feedback! I'm still in my learning phase, and I'll try to make the updates as mentioned. Thanks again for all your support!

You're welcome @SujitSakore. Thanks for your contributions so far.

**Pull request closed without merging**
