### PR TITLE
Implemented Azure Document Intelligence to Extract Content

### LINKED ISSUE #10: Perform OCR with Azure Document Intelligence 📃🧠
# Perform OCR with Azure Document Intelligence 📃🧠

## What is Needed
Contributors are needed to implement an Azure Document Intelligence Solution to optimally extract contents of documents uploaded by the users. To get started with Azure Document Intelligence, you can follow the link here - [Introduction to Azure AI Document Intelligence](https://learn.microsoft.com/en-us/training/modules/intro-to-form-recognizer/?wt.mc_id=studentamb_217190).

## How to Contribute

- Get familiar with the scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
- Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
- Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

## Getting Started
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

### LINKED ISSUE #12: Document Uploads 📝- Large Document Processing
### **Project Overview**
For optimization, there is need to boost the file processing experience by setting a limit on the size of documents uploaded. To avoid delays in response, we need to enforce a page limit on uploaded documents.

### **What is Needed**
Contributors are required to implement a check that ensures documents uploaded have a page limit of 50. This will help mitigate delays when processing large files.

### **How to Contribute**
1. Get familiar with the scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
2. Implement the Page Limit: Modify the file upload logic to ensure documents with more than 50 pages are rejected or flagged.
3. Test your code: Ensure your solution works smoothly before submitting. 
4. Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

### **Getting Started**
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

Looking forward to your solutions! Happy Hacking! 🎉

### PR DESCRIPTION
**Pull request by Odeyiany2**
I added a function to extract content from documents using Azure Document Intelligence and I made the necessary modifications to the main.py file.

### CODE REVIEW

**Review by Sammybams — CHANGES_REQUESTED** [review]
Hi @Odeyiany2, thanks for your contribution. Please can you send samples of how your implementation works so I can merge? You can attach screenshots or maybe a simple recording of how it works and the outputs of your content extraction function.

Also please add all the new environment variables you created to the [.env.example](https://github.com/mlsanigeria/speak-to-docs/blob/main/.env.example) file so others can follow that naming convention. And please beside each of the loading of the environment variables add a comment explaining how you got them. You can as well add the resources you used to the bottom of the contribution guidelines.

Let all import commands be at the top of the script also. Thank you very much.

**Comment by Odeyiany2** [comment]
Okay @Sammybams

**Comment by Odeyiany2** [comment]
Hii @Sammybams I already made the corrections and below is implementation. I also added the resource I used in the contribution.md
[streamlit-main-2024-10-09-11-10-58.webm](https://github.com/user-attachments/assets/1baa4469-dad5-46ed-85f0-07cb1cdfdb95)
Screenshot 2024-10-09 114812
Screenshot 2024-10-09 114821
Screenshot 2024-10-09 114846
Screenshot 2024-10-09 083756

**Review by Sammybams — APPROVED** [review]
Thank you very much for you contribution @Odeyiany2. Amazing work.

**Comment by Sammybams** [comment]
Hello @Odeyiany2, please kindly make a new PR to include the new libraries you used to make use of the Azure Document Intelligence service. You didn't include that in your original PR.

**Pull request merged**
